Add TileEntity registry and TileEntity types
minecraft-cursed-legacy/Cursed-Legacy-API pull request #20
Opened 2020-07-23 19:39 UTC by williambl

Based off the entity registry code.

!!Untested!! works with vanilla. Not tested with custom mod tile entities.

2020-07-24 08:41 UTC, valoeghese commented
Test your code thanks

2020-07-24 08:41 UTC, valoeghese commented
otherwise make it a draft pr :wink:

2020-07-26 21:02 UTC, valoeghese commented
The reason i ask for all PRs to be tested is because of #19, where I assumed it worked since I based it off of one of my mods, but it was broken

2020-07-26 21:24 UTC, williambl commented
Yeah, makes sense. I'll mark as draft once I'm at my pc (or i work out how to do it through the app)

2021-02-13 03:07 UTC, valoeghese commented
Any progress on this?

2021-02-13 03:07 UTC, valoeghese commented
Writing a test mod so we can get this merged as part of 1.0.0 would be cool

2021-02-14 00:05 UTC, williambl commented
Sure I'll look into it

2021-03-14 03:37 UTC, BoogieMonster1O1 commented
any progress on getting this merged?

2021-03-14 11:00 UTC, williambl commented
> any progress on getting this merged?

It's ready, just needs reviews

2021-03-14 13:25 UTC, BoogieMonster1O1 approved these changes
pls merge k thx

2021-04-11 01:33 UTC, valoeghese commented
Can this be retargeted and made into a `tile-entities` module for 1.0.x?
If you have trouble setting up/testing in the multiproject workspace let me know

2021-04-11 01:34 UTC, valoeghese commented
Actually you could probably just add this to the `registries` module tbh

2021-04-11 01:35 UTC, valoeghese commented
You can include other modules for testing using `testImplementation` (see how I do it in attached data)

2021-04-11 01:51 UTC, valoeghese commented
And sorry for making this PR wait so long

2021-04-11 19:48 UTC, valoeghese requested changes
If you can do it in vanilla fine and it uses string ids, the registry seems obselete? If the accessor is still necessary for making a tile entity, please provide an API for using the necessary methods from the accessor in a separate module from registries.

2021-04-11 19:48 UTC, valoeghese commented on src/main/java/io/github/minecraftcursedlegacy/impl/registry/TileEntityTypeRegistry.java
> +	protected void onRemap(TileEntityType remappedValue, int newSerialisedId) {
This seems obselete. TileEntities don't need a registry if they're not stored as an int in vanilla?

2021-04-11 19:50 UTC, valoeghese commented on src/main/java/io/github/minecraftcursedlegacy/impl/registry/TileEntityTypeRegistry.java
> +		AccessorTileEntity.callRegister(remappedValue.getClazz(), remappedValue.getVanillaRegistryStringId());
This seems like the only necessary part of the PR to me.

2021-04-14 22:02 UTC, williambl commented
Superceded by #31

2021-04-14 22:02 UTC, closed without merging